# Generated by Django 3.2.12 on 2025-05-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
