# Generated by Django 3.2.12 on 2025-05-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_alter_teacher_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.courses')),
                ('last_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.video')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.student')),
                ('watched_videos', models.ManyToManyField(blank=True, related_name='watched_by', to='firstapp.video')),
            ],
        ),
    ]
