# Generated by Django 3.2.12 on 2025-05-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_progresstracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstracker',
            name='watched_videos',
        ),
        migrations.AlterField(
            model_name='progresstracker',
            name='last_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.video'),
        ),
    ]
