# Generated by Django 3.2.12 on 2025-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20250529_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='watched_videos',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='firstapp.video'),
        ),
    ]
